serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'prometheus' # Job to scrape Prometheus itself
        static_configs:
          - targets: ['localhost:9090'] # Target for the Prometheus server
      - job_name: 'jboss7' # Job to scrape node_exporter instances
        static_configs:
          - targets: ['jboss.default.svc.cluster.local:19080']
